<?php
/**
 * OfferApi
 * PHP version 7.4
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\negotiation
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Negotiation API
 *
 * The <b>Negotiations API</b> gives sellers the ability to proactively send discount offers to buyers who have shown an \"interest\" in their listings.  <br><br>By sending buyers discount offers on listings where they have shown an interest, sellers can increase the velocity of their sales.  <br><br>There are various ways for a buyer to show <i>interest </i> in a listing. For example, if a buyer adds the listing to their <b>Watch</b> list, or if they add the listing to their shopping cart and later abandon the cart, they are deemed to have shown an interest in the listing.  <br><br>In the offers that sellers send, they can discount their listings by either a percentage off the listing price, or they can set a new discounted price that is lower than the original listing price.  <br><br>For details about how seller offers work, see <a href=\"/api-docs/sell/static/marketing/offers-to-buyers.html\" title=\"Selling Integration Guide\">Sending offers to buyers</a>.
 *
 * The version of the OpenAPI document: v1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace macropage\SDKs\ebay\rest\negotiation\API;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use macropage\SDKs\ebay\rest\negotiation\ApiException;
use macropage\SDKs\ebay\rest\negotiation\Configuration;
use macropage\SDKs\ebay\rest\negotiation\HeaderSelector;
use macropage\SDKs\ebay\rest\negotiation\ObjectSerializer;

/**
 * OfferApi Class Doc Comment
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\negotiation
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OfferApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'findEligibleItems' => [
            'application/json',
        ],
        'sendOfferToInterestedBuyers' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation findEligibleItems
     *
     * @param  string $xEBAYCMARKETPLACEID The eBay marketplace on which you want to search for eligible listings. &lt;br&gt;&lt;br&gt;For a complete list of supported marketplaces, see &lt;a href&#x3D;\&quot;/api-docs/sell/negotiation/overview.html#requirements\&quot; title&#x3D;\&quot;Negotiation API Overview\&quot;&gt;Negotiation API requirements and restrictions&lt;/a&gt;. (required)
     * @param  string $limit This query parameter specifies the maximum number of items to return from the result set on a page in the paginated response. &lt;p&gt;&lt;b&gt;Minimum:&lt;/b&gt; 1 &amp;nbsp; &amp;nbsp;&lt;b&gt;Maximum:&lt;/b&gt; 200 &lt;br&gt;&lt;b&gt;Default: &lt;/b&gt;10&lt;/p&gt; (optional)
     * @param  string $offset This query parameter specifies the number of results to skip in the result set before returning the first result in the paginated response.  &lt;br&gt;&lt;br&gt;Combine &lt;b&gt;offset&lt;/b&gt; with the &lt;b&gt;limit&lt;/b&gt; query parameter to control the items returned in the response. For example, if you supply an &lt;b&gt;offset&lt;/b&gt; of &lt;code&gt;0&lt;/code&gt; and a &lt;b&gt;limit&lt;/b&gt; of &lt;code&gt;10&lt;/code&gt;, the first page of the response contains the first 10 results from the complete list of items retrieved by the call. If &lt;b&gt;offset&lt;/b&gt; is &lt;code&gt;10&lt;/code&gt; and &lt;b&gt;limit&lt;/b&gt; is &lt;code&gt;20&lt;/code&gt;, the first page of the response contains items 11-30 from the complete result set. &lt;br&gt;&lt;br&gt;&lt;b&gt;Default:&lt;/b&gt; 0 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findEligibleItems'] to see the possible values for this operation
     *
     * @throws \macropage\SDKs\ebay\rest\negotiation\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \macropage\SDKs\ebay\rest\negotiation\Model\PagedEligibleItemCollection
     */
    public function findEligibleItems($xEBAYCMARKETPLACEID, $limit = null, $offset = null, string $contentType = self::contentTypes['findEligibleItems'][0])
    {
        list($response) = $this->findEligibleItemsWithHttpInfo($xEBAYCMARKETPLACEID, $limit, $offset, $contentType);
        return $response;
    }

    /**
     * Operation findEligibleItemsWithHttpInfo
     *
     * @param  string $xEBAYCMARKETPLACEID The eBay marketplace on which you want to search for eligible listings. &lt;br&gt;&lt;br&gt;For a complete list of supported marketplaces, see &lt;a href&#x3D;\&quot;/api-docs/sell/negotiation/overview.html#requirements\&quot; title&#x3D;\&quot;Negotiation API Overview\&quot;&gt;Negotiation API requirements and restrictions&lt;/a&gt;. (required)
     * @param  string $limit This query parameter specifies the maximum number of items to return from the result set on a page in the paginated response. &lt;p&gt;&lt;b&gt;Minimum:&lt;/b&gt; 1 &amp;nbsp; &amp;nbsp;&lt;b&gt;Maximum:&lt;/b&gt; 200 &lt;br&gt;&lt;b&gt;Default: &lt;/b&gt;10&lt;/p&gt; (optional)
     * @param  string $offset This query parameter specifies the number of results to skip in the result set before returning the first result in the paginated response.  &lt;br&gt;&lt;br&gt;Combine &lt;b&gt;offset&lt;/b&gt; with the &lt;b&gt;limit&lt;/b&gt; query parameter to control the items returned in the response. For example, if you supply an &lt;b&gt;offset&lt;/b&gt; of &lt;code&gt;0&lt;/code&gt; and a &lt;b&gt;limit&lt;/b&gt; of &lt;code&gt;10&lt;/code&gt;, the first page of the response contains the first 10 results from the complete list of items retrieved by the call. If &lt;b&gt;offset&lt;/b&gt; is &lt;code&gt;10&lt;/code&gt; and &lt;b&gt;limit&lt;/b&gt; is &lt;code&gt;20&lt;/code&gt;, the first page of the response contains items 11-30 from the complete result set. &lt;br&gt;&lt;br&gt;&lt;b&gt;Default:&lt;/b&gt; 0 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findEligibleItems'] to see the possible values for this operation
     *
     * @throws \macropage\SDKs\ebay\rest\negotiation\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \macropage\SDKs\ebay\rest\negotiation\Model\PagedEligibleItemCollection, HTTP status code, HTTP response headers (array of strings)
     */
    public function findEligibleItemsWithHttpInfo($xEBAYCMARKETPLACEID, $limit = null, $offset = null, string $contentType = self::contentTypes['findEligibleItems'][0])
    {
        $request = $this->findEligibleItemsRequest($xEBAYCMARKETPLACEID, $limit, $offset, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\macropage\SDKs\ebay\rest\negotiation\Model\PagedEligibleItemCollection' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\macropage\SDKs\ebay\rest\negotiation\Model\PagedEligibleItemCollection' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\macropage\SDKs\ebay\rest\negotiation\Model\PagedEligibleItemCollection', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\macropage\SDKs\ebay\rest\negotiation\Model\PagedEligibleItemCollection';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\macropage\SDKs\ebay\rest\negotiation\Model\PagedEligibleItemCollection',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findEligibleItemsAsync
     *
     * @param  string $xEBAYCMARKETPLACEID The eBay marketplace on which you want to search for eligible listings. &lt;br&gt;&lt;br&gt;For a complete list of supported marketplaces, see &lt;a href&#x3D;\&quot;/api-docs/sell/negotiation/overview.html#requirements\&quot; title&#x3D;\&quot;Negotiation API Overview\&quot;&gt;Negotiation API requirements and restrictions&lt;/a&gt;. (required)
     * @param  string $limit This query parameter specifies the maximum number of items to return from the result set on a page in the paginated response. &lt;p&gt;&lt;b&gt;Minimum:&lt;/b&gt; 1 &amp;nbsp; &amp;nbsp;&lt;b&gt;Maximum:&lt;/b&gt; 200 &lt;br&gt;&lt;b&gt;Default: &lt;/b&gt;10&lt;/p&gt; (optional)
     * @param  string $offset This query parameter specifies the number of results to skip in the result set before returning the first result in the paginated response.  &lt;br&gt;&lt;br&gt;Combine &lt;b&gt;offset&lt;/b&gt; with the &lt;b&gt;limit&lt;/b&gt; query parameter to control the items returned in the response. For example, if you supply an &lt;b&gt;offset&lt;/b&gt; of &lt;code&gt;0&lt;/code&gt; and a &lt;b&gt;limit&lt;/b&gt; of &lt;code&gt;10&lt;/code&gt;, the first page of the response contains the first 10 results from the complete list of items retrieved by the call. If &lt;b&gt;offset&lt;/b&gt; is &lt;code&gt;10&lt;/code&gt; and &lt;b&gt;limit&lt;/b&gt; is &lt;code&gt;20&lt;/code&gt;, the first page of the response contains items 11-30 from the complete result set. &lt;br&gt;&lt;br&gt;&lt;b&gt;Default:&lt;/b&gt; 0 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findEligibleItems'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findEligibleItemsAsync($xEBAYCMARKETPLACEID, $limit = null, $offset = null, string $contentType = self::contentTypes['findEligibleItems'][0])
    {
        return $this->findEligibleItemsAsyncWithHttpInfo($xEBAYCMARKETPLACEID, $limit, $offset, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findEligibleItemsAsyncWithHttpInfo
     *
     * @param  string $xEBAYCMARKETPLACEID The eBay marketplace on which you want to search for eligible listings. &lt;br&gt;&lt;br&gt;For a complete list of supported marketplaces, see &lt;a href&#x3D;\&quot;/api-docs/sell/negotiation/overview.html#requirements\&quot; title&#x3D;\&quot;Negotiation API Overview\&quot;&gt;Negotiation API requirements and restrictions&lt;/a&gt;. (required)
     * @param  string $limit This query parameter specifies the maximum number of items to return from the result set on a page in the paginated response. &lt;p&gt;&lt;b&gt;Minimum:&lt;/b&gt; 1 &amp;nbsp; &amp;nbsp;&lt;b&gt;Maximum:&lt;/b&gt; 200 &lt;br&gt;&lt;b&gt;Default: &lt;/b&gt;10&lt;/p&gt; (optional)
     * @param  string $offset This query parameter specifies the number of results to skip in the result set before returning the first result in the paginated response.  &lt;br&gt;&lt;br&gt;Combine &lt;b&gt;offset&lt;/b&gt; with the &lt;b&gt;limit&lt;/b&gt; query parameter to control the items returned in the response. For example, if you supply an &lt;b&gt;offset&lt;/b&gt; of &lt;code&gt;0&lt;/code&gt; and a &lt;b&gt;limit&lt;/b&gt; of &lt;code&gt;10&lt;/code&gt;, the first page of the response contains the first 10 results from the complete list of items retrieved by the call. If &lt;b&gt;offset&lt;/b&gt; is &lt;code&gt;10&lt;/code&gt; and &lt;b&gt;limit&lt;/b&gt; is &lt;code&gt;20&lt;/code&gt;, the first page of the response contains items 11-30 from the complete result set. &lt;br&gt;&lt;br&gt;&lt;b&gt;Default:&lt;/b&gt; 0 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findEligibleItems'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findEligibleItemsAsyncWithHttpInfo($xEBAYCMARKETPLACEID, $limit = null, $offset = null, string $contentType = self::contentTypes['findEligibleItems'][0])
    {
        $returnType = '\macropage\SDKs\ebay\rest\negotiation\Model\PagedEligibleItemCollection';
        $request = $this->findEligibleItemsRequest($xEBAYCMARKETPLACEID, $limit, $offset, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findEligibleItems'
     *
     * @param  string $xEBAYCMARKETPLACEID The eBay marketplace on which you want to search for eligible listings. &lt;br&gt;&lt;br&gt;For a complete list of supported marketplaces, see &lt;a href&#x3D;\&quot;/api-docs/sell/negotiation/overview.html#requirements\&quot; title&#x3D;\&quot;Negotiation API Overview\&quot;&gt;Negotiation API requirements and restrictions&lt;/a&gt;. (required)
     * @param  string $limit This query parameter specifies the maximum number of items to return from the result set on a page in the paginated response. &lt;p&gt;&lt;b&gt;Minimum:&lt;/b&gt; 1 &amp;nbsp; &amp;nbsp;&lt;b&gt;Maximum:&lt;/b&gt; 200 &lt;br&gt;&lt;b&gt;Default: &lt;/b&gt;10&lt;/p&gt; (optional)
     * @param  string $offset This query parameter specifies the number of results to skip in the result set before returning the first result in the paginated response.  &lt;br&gt;&lt;br&gt;Combine &lt;b&gt;offset&lt;/b&gt; with the &lt;b&gt;limit&lt;/b&gt; query parameter to control the items returned in the response. For example, if you supply an &lt;b&gt;offset&lt;/b&gt; of &lt;code&gt;0&lt;/code&gt; and a &lt;b&gt;limit&lt;/b&gt; of &lt;code&gt;10&lt;/code&gt;, the first page of the response contains the first 10 results from the complete list of items retrieved by the call. If &lt;b&gt;offset&lt;/b&gt; is &lt;code&gt;10&lt;/code&gt; and &lt;b&gt;limit&lt;/b&gt; is &lt;code&gt;20&lt;/code&gt;, the first page of the response contains items 11-30 from the complete result set. &lt;br&gt;&lt;br&gt;&lt;b&gt;Default:&lt;/b&gt; 0 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findEligibleItems'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findEligibleItemsRequest($xEBAYCMARKETPLACEID, $limit = null, $offset = null, string $contentType = self::contentTypes['findEligibleItems'][0])
    {

        // verify the required parameter 'xEBAYCMARKETPLACEID' is set
        if ($xEBAYCMARKETPLACEID === null || (is_array($xEBAYCMARKETPLACEID) && count($xEBAYCMARKETPLACEID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $xEBAYCMARKETPLACEID when calling findEligibleItems'
            );
        }




        $resourcePath = '/find_eligible_items';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($xEBAYCMARKETPLACEID !== null) {
            $headerParams['X-EBAY-C-MARKETPLACE-ID'] = ObjectSerializer::toHeaderValue($xEBAYCMARKETPLACEID);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendOfferToInterestedBuyers
     *
     * @param  string $xEBAYCMARKETPLACEID The eBay marketplace on which your listings with \&quot;eligible\&quot; buyers appear.  &lt;br&gt;&lt;br&gt;For a complete list of supported marketplaces, see &lt;a href&#x3D;\&quot;/api-docs/sell/negotiation/overview.html#requirements\&quot; title&#x3D;\&quot;Negotiation API Overview\&quot;&gt;Negotiation API requirements and restrictions&lt;/a&gt;. (required)
     * @param  string $contentType This header indicates the format of the request body provided by the client. It&#39;s value should be set to &lt;b&gt;application/json&lt;/b&gt;. &lt;br&gt;&lt;br&gt; For more information, refer to &lt;a href&#x3D;\&quot;/api-docs/static/rest-request-components.html#HTTP\&quot; target&#x3D;\&quot;_blank \&quot;&gt;HTTP request headers&lt;/a&gt;. (required)
     * @param  \macropage\SDKs\ebay\rest\negotiation\Model\CreateOffersRequest $createOffersRequest Send offer to eligible items request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendOfferToInterestedBuyers'] to see the possible values for this operation
     *
     * @throws \macropage\SDKs\ebay\rest\negotiation\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \macropage\SDKs\ebay\rest\negotiation\Model\SendOfferToInterestedBuyersCollectionResponse
     */
    public function sendOfferToInterestedBuyers($xEBAYCMARKETPLACEID, $contentType, $createOffersRequest = null, string $contentType = self::contentTypes['sendOfferToInterestedBuyers'][0])
    {
        list($response) = $this->sendOfferToInterestedBuyersWithHttpInfo($xEBAYCMARKETPLACEID, $contentType, $createOffersRequest, $contentType);
        return $response;
    }

    /**
     * Operation sendOfferToInterestedBuyersWithHttpInfo
     *
     * @param  string $xEBAYCMARKETPLACEID The eBay marketplace on which your listings with \&quot;eligible\&quot; buyers appear.  &lt;br&gt;&lt;br&gt;For a complete list of supported marketplaces, see &lt;a href&#x3D;\&quot;/api-docs/sell/negotiation/overview.html#requirements\&quot; title&#x3D;\&quot;Negotiation API Overview\&quot;&gt;Negotiation API requirements and restrictions&lt;/a&gt;. (required)
     * @param  string $contentType This header indicates the format of the request body provided by the client. It&#39;s value should be set to &lt;b&gt;application/json&lt;/b&gt;. &lt;br&gt;&lt;br&gt; For more information, refer to &lt;a href&#x3D;\&quot;/api-docs/static/rest-request-components.html#HTTP\&quot; target&#x3D;\&quot;_blank \&quot;&gt;HTTP request headers&lt;/a&gt;. (required)
     * @param  \macropage\SDKs\ebay\rest\negotiation\Model\CreateOffersRequest $createOffersRequest Send offer to eligible items request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendOfferToInterestedBuyers'] to see the possible values for this operation
     *
     * @throws \macropage\SDKs\ebay\rest\negotiation\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \macropage\SDKs\ebay\rest\negotiation\Model\SendOfferToInterestedBuyersCollectionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendOfferToInterestedBuyersWithHttpInfo($xEBAYCMARKETPLACEID, $contentType, $createOffersRequest = null, string $contentType = self::contentTypes['sendOfferToInterestedBuyers'][0])
    {
        $request = $this->sendOfferToInterestedBuyersRequest($xEBAYCMARKETPLACEID, $contentType, $createOffersRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\macropage\SDKs\ebay\rest\negotiation\Model\SendOfferToInterestedBuyersCollectionResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\macropage\SDKs\ebay\rest\negotiation\Model\SendOfferToInterestedBuyersCollectionResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\macropage\SDKs\ebay\rest\negotiation\Model\SendOfferToInterestedBuyersCollectionResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\macropage\SDKs\ebay\rest\negotiation\Model\SendOfferToInterestedBuyersCollectionResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\macropage\SDKs\ebay\rest\negotiation\Model\SendOfferToInterestedBuyersCollectionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendOfferToInterestedBuyersAsync
     *
     * @param  string $xEBAYCMARKETPLACEID The eBay marketplace on which your listings with \&quot;eligible\&quot; buyers appear.  &lt;br&gt;&lt;br&gt;For a complete list of supported marketplaces, see &lt;a href&#x3D;\&quot;/api-docs/sell/negotiation/overview.html#requirements\&quot; title&#x3D;\&quot;Negotiation API Overview\&quot;&gt;Negotiation API requirements and restrictions&lt;/a&gt;. (required)
     * @param  string $contentType This header indicates the format of the request body provided by the client. It&#39;s value should be set to &lt;b&gt;application/json&lt;/b&gt;. &lt;br&gt;&lt;br&gt; For more information, refer to &lt;a href&#x3D;\&quot;/api-docs/static/rest-request-components.html#HTTP\&quot; target&#x3D;\&quot;_blank \&quot;&gt;HTTP request headers&lt;/a&gt;. (required)
     * @param  \macropage\SDKs\ebay\rest\negotiation\Model\CreateOffersRequest $createOffersRequest Send offer to eligible items request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendOfferToInterestedBuyers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendOfferToInterestedBuyersAsync($xEBAYCMARKETPLACEID, $contentType, $createOffersRequest = null, string $contentType = self::contentTypes['sendOfferToInterestedBuyers'][0])
    {
        return $this->sendOfferToInterestedBuyersAsyncWithHttpInfo($xEBAYCMARKETPLACEID, $contentType, $createOffersRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendOfferToInterestedBuyersAsyncWithHttpInfo
     *
     * @param  string $xEBAYCMARKETPLACEID The eBay marketplace on which your listings with \&quot;eligible\&quot; buyers appear.  &lt;br&gt;&lt;br&gt;For a complete list of supported marketplaces, see &lt;a href&#x3D;\&quot;/api-docs/sell/negotiation/overview.html#requirements\&quot; title&#x3D;\&quot;Negotiation API Overview\&quot;&gt;Negotiation API requirements and restrictions&lt;/a&gt;. (required)
     * @param  string $contentType This header indicates the format of the request body provided by the client. It&#39;s value should be set to &lt;b&gt;application/json&lt;/b&gt;. &lt;br&gt;&lt;br&gt; For more information, refer to &lt;a href&#x3D;\&quot;/api-docs/static/rest-request-components.html#HTTP\&quot; target&#x3D;\&quot;_blank \&quot;&gt;HTTP request headers&lt;/a&gt;. (required)
     * @param  \macropage\SDKs\ebay\rest\negotiation\Model\CreateOffersRequest $createOffersRequest Send offer to eligible items request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendOfferToInterestedBuyers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendOfferToInterestedBuyersAsyncWithHttpInfo($xEBAYCMARKETPLACEID, $contentType, $createOffersRequest = null, string $contentType = self::contentTypes['sendOfferToInterestedBuyers'][0])
    {
        $returnType = '\macropage\SDKs\ebay\rest\negotiation\Model\SendOfferToInterestedBuyersCollectionResponse';
        $request = $this->sendOfferToInterestedBuyersRequest($xEBAYCMARKETPLACEID, $contentType, $createOffersRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendOfferToInterestedBuyers'
     *
     * @param  string $xEBAYCMARKETPLACEID The eBay marketplace on which your listings with \&quot;eligible\&quot; buyers appear.  &lt;br&gt;&lt;br&gt;For a complete list of supported marketplaces, see &lt;a href&#x3D;\&quot;/api-docs/sell/negotiation/overview.html#requirements\&quot; title&#x3D;\&quot;Negotiation API Overview\&quot;&gt;Negotiation API requirements and restrictions&lt;/a&gt;. (required)
     * @param  string $contentType This header indicates the format of the request body provided by the client. It&#39;s value should be set to &lt;b&gt;application/json&lt;/b&gt;. &lt;br&gt;&lt;br&gt; For more information, refer to &lt;a href&#x3D;\&quot;/api-docs/static/rest-request-components.html#HTTP\&quot; target&#x3D;\&quot;_blank \&quot;&gt;HTTP request headers&lt;/a&gt;. (required)
     * @param  \macropage\SDKs\ebay\rest\negotiation\Model\CreateOffersRequest $createOffersRequest Send offer to eligible items request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendOfferToInterestedBuyers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendOfferToInterestedBuyersRequest($xEBAYCMARKETPLACEID, $contentType, $createOffersRequest = null, string $contentType = self::contentTypes['sendOfferToInterestedBuyers'][0])
    {

        // verify the required parameter 'xEBAYCMARKETPLACEID' is set
        if ($xEBAYCMARKETPLACEID === null || (is_array($xEBAYCMARKETPLACEID) && count($xEBAYCMARKETPLACEID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $xEBAYCMARKETPLACEID when calling sendOfferToInterestedBuyers'
            );
        }

        // verify the required parameter 'contentType' is set
        if ($contentType === null || (is_array($contentType) && count($contentType) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contentType when calling sendOfferToInterestedBuyers'
            );
        }



        $resourcePath = '/send_offer_to_interested_buyers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($xEBAYCMARKETPLACEID !== null) {
            $headerParams['X-EBAY-C-MARKETPLACE-ID'] = ObjectSerializer::toHeaderValue($xEBAYCMARKETPLACEID);
        }
        // header params
        if ($contentType !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($contentType);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($createOffersRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($createOffersRequest));
            } else {
                $httpBody = $createOffersRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
